sonar.projectKey=assignment4
sonar.projectName=assignment4-SonarQube-SonarScanner
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}