pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'docker-hub-cred'
        DOCKERHUB_REPO = 'hechun202601/lectdemo3010_pod_2026'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hechun2024/SEP2_assignment.git'
            }
        }

        stage('Build') {
            steps {
                dir('assignment5-avg_consol') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            environment {
                SONAR_TOKEN = credentials('sonar-token')
            }
            steps {
                dir('assignment5-avg_consol') {
                    withSonarQubeEnv('SonarQubeServer') {
                        sh """
                            ${tool 'SonarScanner'}/bin/sonar-scanner \\
                            -Dsonar.token=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('assignment5-avg_consol') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
                    steps {
                        script {
                            // 使用 withCredentials 获取 Docker Hub 的账号密码
                            withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS_ID}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                                sh """
                                    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                                    docker push ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}
                                    docker logout
                                """
                            }
                        }
                    }
                }
    }
}
