pipeline {
    agent any
    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    environment {
        SONARQUBE_SERVER = 'SonarQubeServer'  // The name of the SonarQube server configured in Jenkins
        SONAR_TOKEN = 'squ_03c04979c1c428885b5e43b477120dba641c0f97' // Store the token securely
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO = 'hechun202601/lectdemo3010_pod_2026'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hechun2024/SEP2_assignment.git'
            }
        }

        stage('Build') {
            steps {
                dir('assignment5-avg_consol') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('assignment5-avg_consol') {
                    withSonarQubeEnv('SonarQubeServer') {
                        sh """
                                    ${tool 'SonarScanner'}/bin/sonar-scanner \\
                                    -Dsonar.projectKey=avg_consol \\
                                    -Dsonar.sources=src \\
                                    -Dsonar.projectName=avg_consol \\
                                    -Dsonar.host.url=http://localhost:9000 \\
                                    -Dsonar.login=${env.SONAR_TOKEN} \\
                                    -Dsonar.java.binaries=target/classes
                                """
                    }
                }
            }
        }



        stage('Build Docker Image') {
            steps {
                dir('assignment5-avg_consol') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                        // Or specify Dockerfile path explicitly if needed
                        // docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}", "-f ./Dockerfile .")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}
