sonar.projectKey=avg_consol
sonar.projectName=avgspd12
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=src/test/java/**
sonar.coverage.exclusions=src/test/java/**
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000

# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=untitled" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"
