sonar.projectKey=assignment3-shopping-cart-localization
sonar.projectName=assignment3-shopping-cart-localization
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml