pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'docker-hub-cred'
        DOCKERHUB_REPO = 'hechun202601/shopping-cart-localization'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Build') {
            steps {
                dir('assignment1-shopping-cart') {
                    sh 'echo PATH=$PATH'
                    sh 'which mvn || true'
                    sh '/opt/homebrew/bin/mvn -v'
                    sh '/opt/homebrew/bin/mvn clean install -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('assignment1-shopping-cart') {
                    sh '/opt/homebrew/bin/mvn test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('assignment1-shopping-cart') {
                    sh '/opt/homebrew/bin/mvn jacoco:report'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                recordCoverage(
                    tools: [[parser: 'JACOCO', pattern: 'assignment1-shopping-cart/target/site/jacoco/jacoco.xml']]
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('assignment1-shopping-cart') {
                    sh '''
                        export PATH=/Applications/Docker.app/Contents/Resources/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
                        echo "PATH=$PATH"
                        which docker
                        which docker-credential-desktop || true
                        docker --version
                        docker build --platform linux/amd64 -t $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: env.DOCKERHUB_CREDENTIALS_ID,
                    usernameVariable: 'DOCKERHUB_USERNAME',
                    passwordVariable: 'DOCKERHUB_PASSWORD'
                )]) {
                    dir('assignment1-shopping-cart') {
                        sh '''
                            export PATH=/Applications/Docker.app/Contents/Resources/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin
                            which docker
                            which docker-credential-desktop || true
                            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                            docker push $DOCKERHUB_REPO:$DOCKER_IMAGE_TAG
                        '''
                    }
                }
            }
        }
}