pipeline {
    agent any

    environment {
        // 1. 必须与在 Jenkins 'Credentials' 里面设置的 ID 完全一致
        DOCKERHUB_CREDENTIALS_ID = 'docker-hub-cred'

        // 2. 修改为你的 Docker Hub 仓库名
        DOCKERHUB_REPO = 'hechun202601/shopping-cart-localization'

        // 3. 标签可以保持 latest，或者改为你的版本号
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                // 4. 修改为自己的 GitHub 仓库地址
                git 'https://github.com/hechun2024/SEP2_assignment.git'
            }
        }

        stage('Build') {
            steps {
                // 如果 Dockerfile 在子目录下，这里需要 cd 进去或者在根目录运行
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Code Coverage') {
            steps {
                sh 'mvn jacoco:report'
            }
        }

        stage('Publish Test Results') {
            steps {
                // 这里的路径要确保能搜到你的测试报告 xml
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // 这里的 '.' 代表 Dockerfile 所在的当前路径
                    docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    // 这里会调用上面定义的 DOCKERHUB_CREDENTIALS_ID 进行登录并推送
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
    post {
            success {
                echo '恭喜！镜像已成功推送到 Docker Hub。'
            }
            failure {
                echo '出错了，请检查 Jenkins 控制台日志。'
            }
        }
}